### ISSUE TITLE
🐛 [dip-21 Scraper]  import-procedure error durch diffHistory

### ISSUE THREAD

**Issue by ManAnRuck** [demokratie-live/democracy-client#1340]
bei aktiviertem diff history scheint der service import-procedures einen Fehler zu schmeißen.

lokal gestartet (mit serverDB) funktioniert es, ausgeführt vom server aus nicht :/

diffHistory ist nötig für die anzeige der history von Beratungszuständen

```
2020-10-22T13:35:21.695418565Z saveProcedure 267898
2020-10-22T13:35:21.696944776Z Mongoose: procedures.findOne({ procedureId: '267898' }, { projection: {} })
2020-10-22T13:35:21.703666463Z Mongoose: procedures.find({ procedureId: '267898' }, { upsert: true, projection: {} })
2020-10-22T13:35:21.713300893Z /app/node_modules/mongodb/lib/core/cursor.js:34
2020-10-22T13:35:21.713342958Z       throw err;
2020-10-22T13:35:21.713351405Z       ^
2020-10-22T13:35:21.713357990Z 
2020-10-22T13:35:21.713364139Z TypeError: Cannot read property '_id' of null
2020-10-22T13:35:21.713370488Z     at objectHash (/app/node_modules/mongoose-diff-history/diffHistory.js:9:38)
2020-10-22T13:35:21.713377076Z     at matchItems (/app/node_modules/jsondiffpatch/src/filters/arrays.js:62:44)
2020-10-22T13:35:21.713384110Z     at lengthMatrix (/app/node_modules/jsondiffpatch/src/filters/lcs.js:30:11)
2020-10-22T13:35:21.713390451Z     at Object.get (/app/node_modules/jsondiffpatch/src/filters/lcs.js:66:16)
2020-10-22T13:35:21.713396660Z     at arraysDiffFilter (/app/node_modules/jsondiffpatch/src/filters/arrays.js:163:17)
2020-10-22T13:35:21.713403417Z     at Pipe.process (/app/node_modules/jsondiffpatch/src/pipe.js:18:5)
2020-10-22T13:35:21.713410016Z     at Processor.process (/app/node_modules/jsondiffpatch/src/processor.js:46:14)
2020-10-22T13:35:21.713441108Z     at DiffPatcher.diff (/app/node_modules/jsondiffpatch/src/diffpatcher.js:46:25)
2020-10-22T13:35:21.713449969Z     at saveDiffObject (/app/node_modules/mongoose-diff-history/diffHistory.js:39:28)
2020-10-22T13:35:21.713456392Z     at saveDiffHistory (/app/node_modules/mongoose-diff-history/diffHistory.js:118:12)
2020-10-22T13:35:21.713462579Z     at /app/node_modules/mongoose-diff-history/diffHistory.js:131:30
2020-10-22T13:35:21.713469075Z     at handleNextResult (/app/node_modules/mongoose/lib/helpers/cursor/eachAsync.js:86:21)
2020-10-22T13:35:21.713475427Z     at /app/node_modules/mongoose/lib/helpers/cursor/eachAsync.js:69:9
2020-10-22T13:35:21.713481590Z     at /app/node_modules/mongoose/lib/cursor/QueryCursor.js:414:5
2020-10-22T13:35:21.713487747Z     at model.Document.init (/app/node_modules/mongoose/lib/document.js:548:5)
2020-10-22T13:35:21.713493993Z     at _create (/app/node_modules/mongoose/lib/cursor/QueryCursor.js:410:12)
2020-10-22T13:35:21.742349588Z error Command failed with exit code 1.
2020-10-22T13:35:21.742543737Z info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by ManAnRuck** [comment]
Aktion: ich deaktiviere dies nun vorerst
