### ISSUE TITLE
Installation issue: Missing configuration scripts?

### ISSUE THREAD

**Issue by roschaefer** [demokratie-live/democracy-client#36]
Description:

I have difficulties with the installation, see below :point_down:  

Faulty Behaviour:

```sh
➜  democracy-client git:(master) yarn install
yarn install v1.3.2
[1/4] Resolving packages...
[2/4] Fetching packages...
info There appears to be trouble with your network connection. Retrying...
[#########################################################################################################################################] 1545/1546%➜  democracy-client git:(master) gst
On branch master
Your branch is up to date with 'origin/master'.
nothing to commit, working tree clean
➜  democracy-client git:(master) yarn start:web
yarn run v1.3.2
$ node ./scripts/start.web.js
module.js:487
    throw err;
    ^
Error: Cannot find module 'react-scripts/config/webpack.config.dev'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/robert/Development/React/democracy-client/scripts/start.web.js:4:27)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Expected Behaviour:

I guess a web server should start?

Steps to reproduce:

- 1. clone repo
- 2. install dependencies
- 3. run `yarn web:start`
- 4. boom :boom:

Commit: [A12B34E](URL)

**Comment by roschaefer** [comment]
Sorry for the false positive: I'm sitting in the train with a low bandwith and there was an issue with `yarn`. Closing
