### ISSUE TITLE
Crash at launch

### ISSUE THREAD

**Issue by Rudloff** [demokratie-live/democracy-client#667]
## 🐛 Bugreport
I built d629dea78fe38fa977593ae21a737de231f935a8 from source but when I try to run it, it crashes after the intro screen:
```
11-08 01:19:45.182  1827  1892 E AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
11-08 01:19:45.182  1827  1892 E AndroidRuntime: Process: de.democracydeutschland.app, PID: 1827
11-08 01:19:45.182  1827  1892 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
11-08 01:19:45.182  1827  1892 E AndroidRuntime: 	at com.facebook.react.modules.blob.BlobModule$2.supports(BlobModule.java:83)
11-08 01:19:45.182  1827  1892 E AndroidRuntime: 	at com.facebook.react.modules.network.NetworkingModule.sendRequest(NetworkingModule.java:257)
11-08 01:19:45.182  1827  1892 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
11-08 01:19:45.182  1827  1892 E AndroidRuntime: 	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:374)
11-08 01:19:45.182  1827  1892 E AndroidRuntime: 	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:162)
11-08 01:19:45.182  1827  1892 E AndroidRuntime: 	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
11-08 01:19:45.182  1827  1892 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:751)
11-08 01:19:45.182  1827  1892 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
11-08 01:19:45.182  1827  1892 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
11-08 01:19:45.182  1827  1892 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
11-08 01:19:45.182  1827  1892 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:194)
11-08 01:19:45.182  1827  1892 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:761)
11-08 01:19:45.184  1763  4161 W ActivityManager:   Force finishing activity de.democracydeutschland.app/com.reactnativenavigation.controllers.NavigationActivity
```

### App-Version & Environment

APP: DEMOCRACY 1.0.5

OS:  Android 7.1.2

### Steps to reproduce
```bash
yarn install
cd android/
gradle assembleProductionRelease
adb install app/build/outputs/apk/app-production-release-unsigned.apk
```

**Comment by ulfgebhardt** [comment]
I replied directly in Gitlab:
https://gitlab.com/fdroid/fdroiddata/merge_requests/3799#note_115485119

**Comment by Rudloff** [comment]
I created an `.env.production` file with the appropriate variables and now it works correctly, thanks!
(Maybe it could be mentionned in [Getting started](https://github.com/demokratie-live/democracy-client#getting-started)?)

**Comment by ulfgebhardt** [comment]
@Rudloff 
Done here: https://github.com/demokratie-live/democracy-client/tree/sprint%2345/readme_gettingstarted
Will be merged in the future, thanks for all your effort
